pipeline {
  environment {
    registry = "ladmusiciankim/jenkinstest"
    registryCredential = 'dockerhub'
  }
  agent any
  stages {
    stage('Building image') {
      steps{
        script {
          echo "Build Test"
        }
      }
    }
  }
}