pipeline {
  agent any
  parameters {
    string(name: 'GIT_URL', defaultValue: 'http://docker.for.mac.host.internal/dj.kim/flask-eve-boilerplate.git')
    string(name: 'GIT_BRANCH', defaultValue: 'master')
  }

  stages {
    stage('Git Checkout') {
      steps{
          println "Git CheckOut Started"
            checkout(
                [
                        $class                           : 'GitSCM',
                        branches                         : [[name: '${GIT_BRANCH}']],
                        doGenerateSubmoduleConfigurations: false,
                        extensions                       : [],
                        submoduleCfg                     : [],
                        userRemoteConfigs                : [[credentialsId: 'gitlab-djkim', url: '${GIT_URL}']]
                ]
            )
        println "Git CheckOut End"
      }
    }
    stage('Docker Build') {
      steps {
        script {
          echo "Build Test"
        }
      }
    }
  }
}